// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schulwebapplikation.Data;

#nullable disable

namespace Schulwebapplikation.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250605090707_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Schulwebapplikation.Models.Klassenraum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCynap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Plaetze")
                        .HasColumnType("INTEGER");

                    b.Property<float>("RaumInQm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Klassenraeume");
                });

            modelBuilder.Entity("Schulwebapplikation.Models.Schueler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Alter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Geburtstag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Geschlecht")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Klasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Schueler");
                });
#pragma warning restore 612, 618
        }
    }
}
